apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "sonarr-config"
  namespace: sonarr
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"