apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "jackett-config"
  namespace: jackett
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"