apiVersion: v1
kind: PersistentVolume
metadata:
  name: "jellyfin-config"
  namespace: jellyfin
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "50Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/sda1/jellyfin/config"