apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "jellyfin-cache"
  namespace: jellyfin
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"