apiVersion: v1
kind: PersistentVolume
metadata:
  name: "jellyfin-family"
  namespace: jellyfin
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "100Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/sda1/jellyfin/family"