apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zimbra-letsencrypt
  namespace: zimbra
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hmedcab@gmail.com
    privateKeySecretRef:
       name: mail-letsencrypt
    solvers:
    - http01:
        ingress:
          class: public
