apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zimbra
  name: zimbra
  namespace: zimbra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zimbra
  template:
    metadata:
      labels:
        app: zimbra
    spec:
      containers:
      - name: zimbra
        image: hectormedina/zimbra:v1
