apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "radarr-config"
  namespace: radarr
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"