apiVersion: v1
kind: PersistentVolume
metadata:
  name: "lidarr-config"
  namespace: lidarr
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "1Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/sda1/lidarr/config"