apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "lidarr-config"
  namespace: lidarr
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"