apiVersion: v1
kind: PersistentVolume
metadata:
  name: "navidrome-data"
  namespace: navidrome
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "1Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/sda1/navidrome/data"