apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "navidrome-data"
  namespace: navidrome
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"