apiVersion: v1
kind: PersistentVolume
metadata:
  name: "wikijs-database-data"
  namespace: wikijs
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "50Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/sda1/wikijs/database-data"