apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "wikijs-database-data"
  namespace: wikijs
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "50Gi"