apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "transmission-downloads"
  namespace: transmission
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "250Gi"